# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  webhooks:
    - webhook: 
    connection: supernode-webhook

pool:
  vmImage: ubuntu-latest


jobs:
- job: 'TESTWEBHOOK'
  displayName: 'TEST WEBHOOK'
  variables:
    CPAP: ${{ parameters.test.CPAP }}
    CPAP_PASS: ${{ parameters.test.CPAP_PASS }}

  steps:
    - task: Bash@3
      displayName: 'echo env'
      inputs:
        targetType: 'inline'
        script: |
          env
