# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

resources:
  webhooks:
    - webhook: test
      connection: supernode-webhook

  repositories:
  - repository: gda-helm-charts
    type: github
    name: L3A-Protocol/gda-helm-charts
    ref: main
    endpoint: L3A-Protocol

pool:
  vmImage: ubuntu-latest

stages:
  - stage: terraformPlan
    pool: 
      vmImage: ubuntu-latest
    jobs:
      - job: 'terraformPlan'
        variables:
          CPAP: ${{ parameters.test.CPAP }}
          CPAP_PASS: ${{ parameters.test.CPAP_PASS }}
      
        steps:
          - task: TerraformInstaller@0
            displayName: 'Terraform Installer'
            inputs:
              terraformVersion: '1.3.3'
          - task: InstallSSHKey@0
            inputs:
              knownHostsEntry: '|1|EG23y3SuKXlyTqS0XGNoI2m813Y=|2I81dE2GnKqyYBPbLU2eVqCEazk= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7Hr1oTWqNqOlzGJOfGJ4NakVyIzf1rXYd4d7wo6jBlkLvCA4odBlL0mDUyZ0/QUfTTqeu+tm22gOsv+VrVTMk6vwRU75gY/y9ut5Mb3bR5BV58dKXyq9A9UeB5Cakehn5Zgm6x1mKoVyf+FFn26iYqXJRgzIZZcZ5V6hrE0Qg39kZm4az48o0AUbf6Sp4SLdvnuMa2sVNwHBboS7EJkm57XQPVU3/QpyNLHbWDdzwtrlS+ez30S3AdYhLKEOxAG8weOnyrtLJAUen9mTkol8oII1edf7mWWbWVf0nBmly21+nZcmCTISQBtdcyPaEno7fFQMDD26/s0lfKob4Kw8H'
              sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC2d/Br/uztS11ATihf9v4VhDJv1oksh/U1XL4BCghJIovplhOg+n5Ls2hay0Tx3hrCNEpwQ4r5cI2vMxv/7+8ki5ha/Zuwte+fv+PwlDvGnVQWjTnzGRgKKNgW3UYkQjWLbZ97lom+cFfSPLKIe3UelAxl2faf9QtASLdpLYMWdwgAB/2MDFQaKkHloN/vukVnQHtPO9b0SpJKELaIvP3gCsJRo2uP8QcnE/NObOp6ZTD1eehlII/H0blp/gbs7MM+gyRNws5PC+9gjQti1Kr6+78/ewJZyNUCb/c7afhMDAkLjEEuqbmXE+Y/xceYEl2E+uejzzewbUrGOFsKw/wLgAEPT57+lKvojwiE0KYvv0xqgSTsQ3wlLZ7FiFGUAiAXsV7rr2VVYuqojFIovDC4Tl3Fm2deuBRuyJc4SwVE0n8+uPLfjrCECOknKx7UFhMdn9LqzkPWDa1aWkvjTcFZ9HTuc8T1+VVHnBQsSW2BXWzV4l+abuznD+dQYMiB4NE='
              sshKeySecureFile: 'sa_id_rsa'
              addEntryToConfig: true
              configHostname: 'github.com'
              configHostAlias: 'github.com'
          - task: Bash@3
            displayName: 'echo env'
            inputs:
              targetType: 'inline'
              script: |
                which terraform
                terraform version
                terraform init
                terraform workspace select test1-v3-ny
                terraform plan
